/**
 * ViewsSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.microsoft.schemas.sharepoint.soap;

public interface ViewsSoap extends java.rmi.Remote {
    public com.microsoft.schemas.sharepoint.soap.GetViewResponseGetViewResult getView(java.lang.String listName, java.lang.String viewName) throws java.rmi.RemoteException;
    public com.microsoft.schemas.sharepoint.soap.GetViewHtmlResponseGetViewHtmlResult getViewHtml(java.lang.String listName, java.lang.String viewName) throws java.rmi.RemoteException;
    public void deleteView(java.lang.String listName, java.lang.String viewName) throws java.rmi.RemoteException;
    public com.microsoft.schemas.sharepoint.soap.AddViewResponseAddViewResult addView(java.lang.String listName, java.lang.String viewName, com.microsoft.schemas.sharepoint.soap.AddViewViewFields viewFields, com.microsoft.schemas.sharepoint.soap.AddViewQuery query, com.microsoft.schemas.sharepoint.soap.AddViewRowLimit rowLimit, java.lang.String type, boolean makeViewDefault) throws java.rmi.RemoteException;
    public com.microsoft.schemas.sharepoint.soap.GetViewCollectionResponseGetViewCollectionResult getViewCollection(java.lang.String listName) throws java.rmi.RemoteException;
    public com.microsoft.schemas.sharepoint.soap.UpdateViewResponseUpdateViewResult updateView(java.lang.String listName, java.lang.String viewName, com.microsoft.schemas.sharepoint.soap.UpdateViewViewProperties viewProperties, com.microsoft.schemas.sharepoint.soap.UpdateViewQuery query, com.microsoft.schemas.sharepoint.soap.UpdateViewViewFields viewFields, com.microsoft.schemas.sharepoint.soap.UpdateViewAggregations aggregations, com.microsoft.schemas.sharepoint.soap.UpdateViewFormats formats, com.microsoft.schemas.sharepoint.soap.UpdateViewRowLimit rowLimit) throws java.rmi.RemoteException;
    public com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlResponseUpdateViewHtmlResult updateViewHtml(java.lang.String listName, java.lang.String viewName, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlViewProperties viewProperties, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlToolbar toolbar, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlViewHeader viewHeader, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlViewBody viewBody, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlViewFooter viewFooter, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlViewEmpty viewEmpty, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlRowLimitExceeded rowLimitExceeded, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlQuery query, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlViewFields viewFields, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlAggregations aggregations, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlFormats formats, com.microsoft.schemas.sharepoint.soap.UpdateViewHtmlRowLimit rowLimit) throws java.rmi.RemoteException;
    public com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2ResponseUpdateViewHtml2Result updateViewHtml2(java.lang.String listName, java.lang.String viewName, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2ViewProperties viewProperties, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2Toolbar toolbar, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2ViewHeader viewHeader, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2ViewBody viewBody, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2ViewFooter viewFooter, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2ViewEmpty viewEmpty, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2RowLimitExceeded rowLimitExceeded, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2Query query, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2ViewFields viewFields, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2Aggregations aggregations, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2Formats formats, com.microsoft.schemas.sharepoint.soap.UpdateViewHtml2RowLimit rowLimit, java.lang.String openApplicationExtension) throws java.rmi.RemoteException;
}
